---
# tasks file for remove-config-from-bareos-server

- name: "Remove backup folder {{ archive_device }}"
  become: true
  become_method: sudo
  file:
    path: "{{ archive_device }}"
    state: absent
    owner: bareos
    group: bareos
    mode: 0750

- name: "Removing config files from Bareos Server"
  become: true
  become_method: sudo
  file: 
    path: "{{ item }}" 
    state: absent
  with_items:
      - "/etc/bareos/bareos-dir.d/client/{{ host_name }}-fd.conf" 
      - "/etc/bareos/bareos-dir.d/fileset/{{ host_name }}-FileSet.conf" 
      - "/etc/bareos/bareos-dir.d/job/{{ host_name }}-Backup.conf" 
      - "/etc/bareos/bareos-dir.d/jobdefs/{{ host_name }}-JobDefs.conf"  
      - "/etc/bareos/bareos-dir.d/pool/{{ host_name }}-Full-Pool.conf" 
      - "/etc/bareos/bareos-dir.d/pool/{{ host_name }}-Incremental-Pool.conf" 
      - "/etc/bareos/bareos-dir.d/schedule/{{ host_name }}-Schedule.conf" 
      - "/etc/bareos/bareos-sd.d/device/File-{{ host_name }}-Storage.conf"  
      - "/etc/bareos/bareos-dir.d/storage/{{ host_name }}-Storage.conf"  
  notify: "restart bareos all"

- name: "Debug Statement"
  debug:
   msg: "The files should now be deleted. This is required to trigger that notify for some reason."
  notify: "restart bareos all"




